import type { Business } from "@/interfaces/business.interface";

const businesses: Business[] = [
    {
        id: "1",
        name: "Barbearia Moderna",
        slug: "barbearia-moderna",
        description:
            "A melhor barbearia da região! Oferecemos cortes modernos, barba bem feita e um atendimento diferenciado. Nossa equipe é formada por profissionais experientes e apaixonados pelo que fazem.",
        logo: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=200&h=200&fit=crop",
        coverImage:
            "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1200&h=400&fit=crop",
        category: "Barbearia",
        phone: "(11) 98765-4321",
        email: "contato@barbeariamoderna.com.br",
        website: "https://barbeariamoderna.com.br",
        address: {
            street: "Rua Augusta",
            number: "1234",
            complement: "Loja 2",
            neighborhood: "Consolação",
            city: "São Paulo",
            state: "SP",
            zipCode: "01304-001",
            country: "Brasil",
        },
        socialMedia: {
            instagram: "@barbeariamoderna",
            facebook: "barbeariamoderna",
        },
        businessHours: {
            monday: { open: "09:00", close: "19:00" },
            tuesday: { open: "09:00", close: "19:00" },
            wednesday: { open: "09:00", close: "19:00" },
            thursday: { open: "09:00", close: "19:00" },
            friday: { open: "09:00", close: "20:00" },
            saturday: { open: "09:00", close: "18:00" },
            sunday: { closed: true },
        },
        rating: {
            average: 4.8,
            count: 127,
        },
        reviews: [
            {
                id: "r1",
                businessId: "1",
                customerName: "Carlos Silva",
                rating: 5,
                comment:
                    "Excelente atendimento! O corte ficou perfeito e o ambiente é muito agradável. Recomendo!",
                serviceType: "Corte de Cabelo",
                date: "2025-09-15T10:00:00.000Z",
                response: {
                    text: "Muito obrigado Carlos! Ficamos felizes em atendê-lo. Volte sempre!",
                    date: "2025-09-15T14:30:00.000Z",
                },
            },
            {
                id: "r2",
                businessId: "1",
                customerName: "Pedro Santos",
                rating: 5,
                comment: "Melhor barbearia da região! Profissionais qualificados e preço justo.",
                serviceType: "Corte + Barba",
                date: "2025-09-10T15:30:00.000Z",
            },
            {
                id: "r3",
                businessId: "1",
                customerName: "João Oliveira",
                rating: 4,
                comment: "Bom atendimento, ambiente limpo. Única ressalva é que às vezes demora um pouco.",
                serviceType: "Corte de Cabelo",
                date: "2025-09-05T11:20:00.000Z",
            },
        ],
        planType: "business",
        ownerId: 1,
        createdAt: "2024-01-15T00:00:00.000Z",
        updatedAt: "2025-10-01T00:00:00.000Z",
    },
    {
        id: "2",
        name: "Salão Elegante",
        slug: "salao-elegante",
        description:
            "Salão de beleza completo com serviços de cabelo, manicure, pedicure e estética. Atendemos homens e mulheres com hora marcada.",
        logo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200&h=200&fit=crop",
        coverImage:
            "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=1200&h=400&fit=crop",
        category: "Salão de Beleza",
        phone: "(11) 91234-5678",
        email: "contato@salaoelegante.com.br",
        address: {
            street: "Av. Paulista",
            number: "2000",
            neighborhood: "Bela Vista",
            city: "São Paulo",
            state: "SP",
            zipCode: "01310-200",
            country: "Brasil",
        },
        socialMedia: {
            instagram: "@salaoelegante",
            facebook: "salaoelegante",
        },
        businessHours: {
            monday: { open: "09:00", close: "18:00" },
            tuesday: { open: "09:00", close: "18:00" },
            wednesday: { open: "09:00", close: "18:00" },
            thursday: { open: "09:00", close: "18:00" },
            friday: { open: "09:00", close: "19:00" },
            saturday: { open: "09:00", close: "17:00" },
            sunday: { closed: true },
        },
        rating: {
            average: 4.6,
            count: 89,
        },
        reviews: [
            {
                id: "r4",
                businessId: "2",
                customerName: "Maria Fernanda",
                rating: 5,
                comment: "Adorei o resultado! As meninas são super atenciosas e o ambiente é lindo.",
                serviceType: "Manicure",
                date: "2025-09-20T14:00:00.000Z",
            },
            {
                id: "r5",
                businessId: "2",
                customerName: "Ana Paula",
                rating: 4,
                comment: "Bom salão, preços acessíveis. Voltarei com certeza!",
                serviceType: "Corte Feminino",
                date: "2025-09-18T16:30:00.000Z",
            },
        ],
        planType: "business",
        ownerId: 2,
        createdAt: "2024-02-20T00:00:00.000Z",
        updatedAt: "2025-10-01T00:00:00.000Z",
    },
    {
        id: "3",
        name: "Clínica Bem-Estar",
        slug: "clinica-bem-estar",
        description:
            "Clínica de estética e bem-estar. Oferecemos massagens relaxantes, limpeza de pele, drenagem linfática e muito mais.",
        logo: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=200&h=200&fit=crop",
        coverImage:
            "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&h=400&fit=crop",
        category: "Clínica de Estética",
        phone: "(11) 93456-7890",
        email: "contato@clinicabemestar.com.br",
        address: {
            street: "Rua Oscar Freire",
            number: "500",
            neighborhood: "Jardins",
            city: "São Paulo",
            state: "SP",
            zipCode: "01426-001",
            country: "Brasil",
        },
        socialMedia: {
            instagram: "@clinicabemestar",
        },
        businessHours: {
            monday: { open: "08:00", close: "20:00" },
            tuesday: { open: "08:00", close: "20:00" },
            wednesday: { open: "08:00", close: "20:00" },
            thursday: { open: "08:00", close: "20:00" },
            friday: { open: "08:00", close: "20:00" },
            saturday: { open: "09:00", close: "15:00" },
            sunday: { closed: true },
        },
        rating: {
            average: 4.9,
            count: 156,
        },
        reviews: [
            {
                id: "r6",
                businessId: "3",
                customerName: "Juliana Costa",
                rating: 5,
                comment:
                    "Melhor massagem que já fiz! Ambiente tranquilo e profissionais super capacitados.",
                serviceType: "Massagem Relaxante",
                date: "2025-09-25T10:30:00.000Z",
            },
            {
                id: "r7",
                businessId: "3",
                customerName: "Fernanda Lima",
                rating: 5,
                comment: "Adoro esta clínica! Sempre saio renovada. Recomendo demais!",
                serviceType: "Limpeza de Pele",
                date: "2025-09-22T15:00:00.000Z",
            },
        ],
        planType: "individual",
        ownerId: 3,
        createdAt: "2024-03-10T00:00:00.000Z",
        updatedAt: "2025-10-01T00:00:00.000Z",
    },
];

export default businesses;
