import type { Company, Subscription, PlanConfig } from "@/interfaces/company.interface";

export const companies: Company[] = [
    {
        id: "comp-001",
        name: "Salão Bella Vista",
        email: "contato@bellavista.com.br",
        phone: "+55 11 98765-4321",
        document: "12.345.678/0001-90",
        country: "BR",
        planType: "business",
        status: "active",
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-12-01T15:30:00Z",
        ownerId: 1,
        ownerName: "Maria Silva",
        ownerEmail: "business@schedfy.com",
        stats: {
            totalAppointments: 1250,
            totalRevenue: 125000.00,
            activeProfessionals: 8,
            totalServices: 25,
        },
    },
    {
        id: "comp-002",
        name: "Studio Ana Costa",
        email: "ana@studiocosmetics.com.br",
        phone: "+55 21 99876-5432",
        document: "23.456.789/0001-01",
        country: "BR",
        planType: "individual",
        status: "active",
        createdAt: "2024-03-20T14:00:00Z",
        updatedAt: "2025-01-10T09:00:00Z",
        ownerId: 2,
        ownerName: "Ana Costa",
        ownerEmail: "individual@schedfy.com",
        stats: {
            totalAppointments: 320,
            totalRevenue: 28800.00,
            activeProfessionals: 1,
            totalServices: 12,
        },
    },
    {
        id: "comp-003",
        name: "Barbearia Moderna",
        email: "contato@barberiamoderna.com.br",
        phone: "+55 11 91234-5678",
        document: "34.567.890/0001-12",
        country: "BR",
        planType: "simple_booking",
        status: "active",
        createdAt: "2024-06-01T11:00:00Z",
        updatedAt: "2025-01-05T16:00:00Z",
        ownerId: 5,
        ownerName: "João Santos",
        ownerEmail: "simple@schedfy.com",
        stats: {
            totalAppointments: 580,
            totalRevenue: 34800.00,
            activeProfessionals: 3,
            totalServices: 8,
        },
    },
    {
        id: "comp-004",
        name: "Beauty Lounge Lisboa",
        email: "info@beautylounge.pt",
        phone: "+351 21 234-5678",
        document: "123456789",
        country: "PT",
        planType: "business",
        status: "trial",
        createdAt: "2025-01-01T08:00:00Z",
        updatedAt: "2025-01-08T12:00:00Z",
        ownerId: 10,
        ownerName: "Sofia Ferreira",
        ownerEmail: "sofia@beautylounge.pt",
        stats: {
            totalAppointments: 45,
            totalRevenue: 3600.00,
            activeProfessionals: 5,
            totalServices: 18,
        },
    },
    {
        id: "comp-005",
        name: "The Spa NYC",
        email: "contact@thespanyc.com",
        phone: "+1 212-555-0123",
        document: "12-3456789",
        country: "US",
        planType: "business",
        status: "suspended",
        createdAt: "2024-02-10T13:00:00Z",
        updatedAt: "2024-12-15T10:00:00Z",
        ownerId: 15,
        ownerName: "Jennifer Smith",
        ownerEmail: "jennifer@thespanyc.com",
        stats: {
            totalAppointments: 890,
            totalRevenue: 89000.00,
            activeProfessionals: 12,
            totalServices: 30,
        },
    },
];

export const subscriptions: Subscription[] = [
    {
        id: "sub-001",
        companyId: "comp-001",
        planType: "business",
        status: "active",
        startDate: "2024-01-15T10:00:00Z",
        billingCycle: "monthly",
        currency: "BRL",
        amount: 499.00,
        nextBillingDate: "2025-02-15T10:00:00Z",
        paymentMethod: {
            type: "credit_card",
            last4: "4242",
            brand: "Visa",
        },
    },
    {
        id: "sub-002",
        companyId: "comp-002",
        planType: "individual",
        status: "active",
        startDate: "2024-03-20T14:00:00Z",
        billingCycle: "yearly",
        currency: "BRL",
        amount: 2388.00, // 249 * 12 - 20% discount
        nextBillingDate: "2026-03-20T14:00:00Z",
        paymentMethod: {
            type: "pix",
        },
    },
    {
        id: "sub-003",
        companyId: "comp-003",
        planType: "simple_booking",
        status: "active",
        startDate: "2024-06-01T11:00:00Z",
        billingCycle: "monthly",
        currency: "BRL",
        amount: 149.00,
        nextBillingDate: "2025-02-01T11:00:00Z",
        paymentMethod: {
            type: "credit_card",
            last4: "1234",
            brand: "Mastercard",
        },
    },
    {
        id: "sub-004",
        companyId: "comp-004",
        planType: "business",
        status: "trial",
        startDate: "2025-01-01T08:00:00Z",
        trialEndDate: "2025-01-15T08:00:00Z",
        billingCycle: "monthly",
        currency: "EUR",
        amount: 89.00,
        nextBillingDate: "2025-02-01T08:00:00Z",
    },
    {
        id: "sub-005",
        companyId: "comp-005",
        planType: "business",
        status: "canceled",
        startDate: "2024-02-10T13:00:00Z",
        endDate: "2024-12-15T10:00:00Z",
        billingCycle: "monthly",
        currency: "USD",
        amount: 99.00,
        nextBillingDate: "2024-12-15T10:00:00Z",
        canceledAt: "2024-12-15T10:00:00Z",
        cancelReason: "Payment failure - multiple attempts",
        paymentMethod: {
            type: "credit_card",
            last4: "5555",
            brand: "Amex",
        },
    },
];

export const planConfigs: PlanConfig[] = [
    {
        id: "simple_booking",
        name: "Simple Booking",
        description: "Perfeito para pequenos negócios com agendamentos básicos",
        features: [
            "Até 3 atendentes",
            "Agendamento online",
            "Gestão de serviços",
            "Notificações por email",
            "Suporte por email",
        ],
        limits: {
            maxProfessionals: 3,
            maxServices: 15,
            maxAppointmentsPerMonth: 200,
        },
        pricing: {
            USD: { monthly: 29, yearly: 278 }, // ~20% discount
            EUR: { monthly: 27, yearly: 259 },
            BRL: { monthly: 149, yearly: 1430 },
        },
        commission: {
            percentage: 3, // 3% commission
        },
    },
    {
        id: "individual",
        name: "Individual",
        description: "Ideal para profissionais autônomos",
        features: [
            "1 profissional (você)",
            "Agendamento online ilimitado",
            "Gestão de serviços ilimitada",
            "Notificações por email e SMS",
            "Análises básicas",
            "Suporte prioritário",
        ],
        limits: {
            maxProfessionals: 1,
            maxServices: "unlimited",
            maxAppointmentsPerMonth: "unlimited",
        },
        pricing: {
            USD: { monthly: 49, yearly: 470 },
            EUR: { monthly: 45, yearly: 432 },
            BRL: { monthly: 249, yearly: 2388 },
        },
        commission: {
            percentage: 2.5,
        },
    },
    {
        id: "business",
        name: "Business",
        description: "Solução completa para empresas com equipe",
        features: [
            "Profissionais ilimitados",
            "Agendamento online ilimitado",
            "Gestão completa de serviços",
            "Notificações por email e SMS",
            "Análises avançadas",
            "Sistema de comissões",
            "Gestão de promoções",
            "Integração com pagamentos",
            "Suporte premium 24/7",
            "API de integração",
        ],
        limits: {
            maxProfessionals: "unlimited",
            maxServices: "unlimited",
            maxAppointmentsPerMonth: "unlimited",
        },
        pricing: {
            USD: { monthly: 99, yearly: 950 },
            EUR: { monthly: 89, yearly: 854 },
            BRL: { monthly: 499, yearly: 4790 },
        },
        commission: {
            percentage: 2,
        },
    },
];

export default companies;
