import type { Service } from "@/interfaces/service.interface";

export const services: Service[] = [
    {
        id: 1,
        name: "Corte de Cabelo",
        description: "Corte de cabelo masculino ou feminino.",
        duration: 30,
        price: 25.00,
        commerceId: 1,
        isActive: true,
        requiresConfirmation: false,
        commissionPercentage: 0,
        allowDiscounts: false,
        availableDays: []
    },
    {
        id: 2,
        name: "Manicure",
        description: "Serviço de manicure e pedicure.",
        duration: 45,
        price: 30.00,
        commerceId: 1,
        isActive: true,
        requiresConfirmation: true,
        commissionPercentage: 0,
        allowDiscounts: false,
        availableDays: [],
        professionals: [2, 5], 
    },
    {
        id: 3,
        name: "Massagem Relaxante",
        description: "Massagem corporal para relaxamento.",
        duration: 60,
        price: 70.00,
        commerceId: 1,
        isActive: true,
        requiresConfirmation: true,
        commissionPercentage: 0,
        allowDiscounts: false,
        availableDays: [],
        professionals: [5, 6], 
    },
    {
        id: 4,
        name: "Consulta Médica",
        description: "Consulta com médico generalista.",
        duration: 30,
        price: 100.00,
        commerceId: 1,
        isActive: true,
        requiresConfirmation: true,
        commissionPercentage: 0,
        allowDiscounts: false,
        availableDays: [],
        professionals: [1, 6], 
    },
    {
        id: 5,
        name: "Aula de Yoga",
        description: "Aula de yoga para iniciantes.",
        duration: 60,
        price: 20.00,
        commerceId: 1,
        isActive: true,
        requiresConfirmation: false,
        commissionPercentage: 0,
        allowDiscounts: false,
        availableDays: [],
        professionals: [3], 
    },
];
